name: Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS and Mac
    runs-on: macos-26

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "26.0"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Install Workloads
      run: dotnet workload restore CrossIntelligence.sln

    - name: Set package Version from run number
      shell: bash
      run: sed -i '' -E 's#(<Version>)([0-9]+\.[0-9]+)\.[0-9]+(</Version>)#\1\2.'"${GITHUB_RUN_NUMBER}"'\3#' CrossIntelligence/CrossIntelligence.csproj

    - name: Build
      run: dotnet build -f net9.0-ios26.0 -c Release CrossIntelligence/CrossIntelligence.csproj

    - name: Package
      run: dotnet pack -c Release -o PackageOut CrossIntelligence/CrossIntelligence.csproj

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CrossIntelligenceNuGetPackage
        path: ./PackageOut
