name: Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS and Mac
    runs-on: macos-15

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "26.0-beta"

    - name: Download iOS SDK
      run: xcodebuild -downloadPlatform iOS

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Install Workloads
      run: dotnet workload restore CrossIntelligence.sln

    - name: Build
      run: dotnet build -c Release CrossIntelligence/CrossIntelligence.csproj
